
; ------ Starting here,	not logged in CDL ------
    .BYTE $FF
    .BYTE $32 ;	2
    .BYTE $7F
    .BYTE $7F
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FE
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $7F
    .BYTE $22
    .BYTE $FE
    .BYTE   2
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE $82
    .BYTE $FB
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FB
    .BYTE $82
    .BYTE $FB
    .BYTE $FF
    .BYTE $82
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FB
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $77
    .BYTE   2
    .BYTE $F7
    .BYTE   8
    .BYTE $F7
    .BYTE   8
    .BYTE $FD
    .BYTE   0
    .BYTE $FD
    .BYTE $12
    .BYTE $FF
    .BYTE $FF
    .BYTE   0
    .BYTE $75
    .BYTE   0
    .BYTE $F7
    .BYTE   0
    .BYTE $FF
    .BYTE $80
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FB
    .BYTE   8
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $77
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE   2
    .BYTE $FD
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $FF
    .BYTE   8
    .BYTE $FF
    .BYTE $40
    .BYTE $F5
    .BYTE   0
    .BYTE $F9
    .BYTE $80
    .BYTE $FF
    .BYTE  $A
    .BYTE $FF
    .BYTE $FF
    .BYTE   0
    .BYTE $7D
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $7F
    .BYTE  $A
    .BYTE   0
    .BYTE $7D
    .BYTE   2
    .BYTE $FD
    .BYTE   2
    .BYTE $F5
    .BYTE $10
    .BYTE $FD
    .BYTE   0
    .BYTE $FD
    .BYTE $20
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE $20
    .BYTE $FD
    .BYTE $7D
    .BYTE $10
    .BYTE $F5
    .BYTE   0
    .BYTE $F5
    .BYTE   0
    .BYTE $7D
    .BYTE   0
    .BYTE $7D
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $12
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE $12
    .BYTE $F7
    .BYTE $12
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE $FF
    .BYTE   0
    .BYTE $7F
    .BYTE $92
    .BYTE $FF
    .BYTE $22
    .BYTE $7F
    .BYTE $12
    .BYTE $FF
    .BYTE $10
    .BYTE $FE
    .BYTE   0
    .BYTE $FF
    .BYTE $92
    .BYTE $7F
    .BYTE   2
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE $7E
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE   4
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE $22
    .BYTE $F7
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE $77
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $B7
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE $12
    .BYTE $A2
    .BYTE $FF
    .BYTE $12
    .BYTE $7F
    .BYTE   2
    .BYTE $77
    .BYTE $22
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $7F
    .BYTE   2
    .BYTE $7E
    .BYTE $7F
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FE
    .BYTE   2
    .BYTE $FE
    .BYTE   2
    .BYTE $7F
    .BYTE $20
    .BYTE $7F
    .BYTE   0
    .BYTE $3E
    .BYTE $86
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FB
    .BYTE $10
    .BYTE $FF
    .BYTE   0
    .BYTE $FB
    .BYTE   2
    .BYTE $FF
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE   0
    .BYTE $77
    .BYTE   8
    .BYTE $7D
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $3F
    .BYTE $80
    .BYTE $7F
    .BYTE $10
    .BYTE $FB
    .BYTE   8
    .BYTE $77
    .BYTE $C0
    .BYTE $FD
    .BYTE $7F
    .BYTE   0
    .BYTE $F7
    .BYTE   2
    .BYTE $F7
    .BYTE   0
    .BYTE $7D
    .BYTE $82
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE $82
    .BYTE $FF
    .BYTE $FF
    .BYTE   2
    .BYTE $FB
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $BF
    .BYTE   2
    .BYTE   0
    .BYTE $F7
    .BYTE   0
    .BYTE $FF
    .BYTE $10
    .BYTE $F7
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE $FB
    .BYTE   8
    .BYTE $FF
    .BYTE   8
    .BYTE $B7
    .BYTE  $A
    .BYTE $FF
    .BYTE $7F
    .BYTE   0
    .BYTE $F3
    .BYTE   0
    .BYTE $F7
    .BYTE   0
    .BYTE $F7
    .BYTE $82
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $7F
    .BYTE $40
    .BYTE   2
    .BYTE $FF
    .BYTE   6
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   0
    .BYTE $7F
    .BYTE   0
    .BYTE $FF
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $FF
    .BYTE   6
    .BYTE $FF
    .BYTE   2
    .BYTE $F7
    .BYTE   4
    .BYTE $7F
    .BYTE   0
    .BYTE $7F
    .BYTE   2
    .BYTE $82
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE $FF
    .BYTE   0
    .BYTE $FF
    .BYTE   2
    .BYTE $FD
    .BYTE $82
    .BYTE $7F
    .BYTE   2
    .BYTE $7F
    .BYTE $12
    .BYTE $7F
    .BYTE $77
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $7E
    .BYTE   0
    .BYTE $77
    .BYTE $82
    .BYTE $7F
    .BYTE   2
    .BYTE $F7
    .BYTE   2
    .BYTE $FF
    .BYTE   2
    .BYTE $7F
    .BYTE   2
    .BYTE   2
    .BYTE $FD
    .BYTE   2
    .BYTE $FD
    .BYTE $12
    .BYTE $F5
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $FF
    .BYTE   0
    .BYTE $F7
    .BYTE $10
    .BYTE $FD
    .BYTE $F5
    .BYTE   0
    .BYTE $FD
    .BYTE $10
    .BYTE $FD
    .BYTE $82
    .BYTE $FD
    .BYTE   0
    .BYTE $FD
    .BYTE   0
    .BYTE $FF
    .BYTE $80
    .BYTE $F5
    .BYTE   0
    .BYTE $FD
    .BYTE $80
; ------ Ending	here, not logged in CDL	------
